export const userList = [
  {
    id: 1,
    productName:
      "Chicken Breast Fillets, Boneless matuu maMarinated 6 Ounce Raw, Invivid",
    brand: "Hormel Black Labelmany",
    price: "$60.67 / 6*1LB",
    quantity: "0 * 6 * 1LB",
    total: "0",
    status: "",
  },
  {
    id: 2,
    productName: "Beef Burger Patties",
    brand: "Hormel Black Labelmany",
    price: "$60.67 / 6*1LB",
    quantity: "15 * 6 * 1LB",
    total: "$9000.88",
    status: "",
  },
  {
    id: 3,
    productName: "Pork Sausages",
    brand: "Hormel Black Labelmany",
    price: "$60.67 / 6*1LB",
    quantity: "13 * 6 * 1LB",
    total: "12,654.32",
    status: "",
  },
  {
    id: 4,
    productName: "Mixed Seafood Platter",
    brand: "Hormel Black Labelmany",
    price: "$60.67 / 6*1LB",
    quantity: "13 * 6 * 1LB",
    total: "12,654.32",
    status: "",
  },
  {
    id: 5,
    productName: "Boneless matuu maMarinated 6 Ounce Raw, Invivid",
    brand: "Hormel Black Labelmany",
    price: "$60.67 / 6 * 1LB",
    quantity: "13 * 6 * 1LB",
    total: "12,654.32",
    status: "",
  },
  {
    id: 6,
    productName: "Shrimp Scampi",
    brand: "Hormel Black Labelmany",
    price: "$60.67 / 6 * 1LB",
    quantity: "13 * 6 * 1LB",
    total: "12,654.32",
    status: "",
  },
];
